name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-locally:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install uv
      run: make install-uv
    - name: Lint and test
      run: make

  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t isaric-arcmapper .

      - name: Run Docker container
        run: |
          docker run -d -p 80:8050 --name isaric-arcmapper isaric-arcmapper

      - name: Wait for container to be ready
        run: |
          sleep 5

      - name: Check if container is running
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' isaric-arcmapper)" != "true" ]; then
            exit 1
          fi

      - name: Check if app is responding
        run: |
          for i in {1..10}; do
            if curl -sSf http://localhost:80 >/dev/null; then
              echo "App responding"
              exit 0
            fi
            echo "Waiting for app to be ready..."
            sleep 2
          done
          exit 1

      - name: Stop and remove container
        run: |
          docker stop isaric-arcmapper
          docker rm isaric-arcmapper
  